{% set version = "2.3.10" %}

package:
  name: pybox2d
  version: {{ version }}

source:
  url: https://github.com/pybox2d/pybox2d/archive/{{ version }}.tar.gz
  sha256: 5471722f290b7285dcbdee9bef61d1cb424e5a610fa6e19e9ddeb854c7e3b937

build:
  number: 8

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - swig
    - python                                # [build_platform != target_platform]
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - Box2D
    - Box2D.b2

about:
  home: https://github.com/pybox2d/pybox2d
  doc_url: https://github.com/pybox2d/pybox2d/wiki/manual
  dev_url: https://github.com/pybox2d/pybox2d
  summary: Python Box2D - a 2D physics engine for games
  license: zlib-acknowledgement
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kne
